create table if not exists public.city_cache (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  endpoint text not null,
  params jsonb not null default '{}'::jsonb,
  response_data jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null
);

create index if not exists city_cache_expires_at_idx
  on public.city_cache (expires_at);

create index if not exists city_cache_endpoint_idx
  on public.city_cache (endpoint);

create table if not exists public.city_cache_cleanup_logs (
  id bigint generated by default as identity primary key,
  cleanup_date timestamptz not null default timezone('utc', now()),
  deleted_entries integer not null default 0,
  cleanup_duration_ms integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.city_cache enable row level security;
alter table public.city_cache_cleanup_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'city_cache'
      and policyname = 'city_cache_public_access'
  ) then
    create policy city_cache_public_access
      on public.city_cache
      for all
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'city_cache_cleanup_logs'
      and policyname = 'city_cache_cleanup_logs_public_access'
  ) then
    create policy city_cache_cleanup_logs_public_access
      on public.city_cache_cleanup_logs
      for all
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;
